#Target : Dependencies
#<TAB>commands

Build : Project_main.c Unit_Convertion.c
	gcc Project_main.c Unit_Convertion.c -o Unit_Convertion.out
	
Run : Build
	./Unit_Convertion.out

Clean:
	rm -rf *.o *.out *.i *.s

