#Target : Dependencies
#<TAB>commands

Build : Project_main.c Unit_Convertion.c test_Unit_convertion.c unity.c
	gcc Project_main.c Unit_Convertion.c test_Unit_convertion.c unity.c -o Unit_Convertion.out -lm
	
Run : Build
	./Unit_Convertion.out

Clean:
	rm -rf *.o *.out *.i *.s

